name: Deployar Angular Chat Redes Sociales en Amazon S3

on:
  push:
    branches:
      - master
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checando que todo ok
      uses: actions/checkout@v2

    - name: Instalando Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Instalando Yarn
      run: npm install -g yarn

    - name: Instalando todo lo necesario del proyecto Angular
      run: yarn install

    - name: Construyendo proyecto Angular y creando archivo .war
      run: yarn war

    - name: Configurando AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Subiendo archivo .war a Amazon S3
      run: aws s3 cp dist/ANGULAR_SEEKOP_BI_ADMININTERFACES_SOCIALMEDIA_CHAT.war s3://sicop-apps/bi-admin-interfaces-redessociales-chat/ANGULAR_SEEKOP_BI_ADMININTERFACES_SOCIALMEDIA_CHAT.war
