name: Desplegar Angular Chat Redes Sociales en Amazon S3

on:
  push:
    branches:
      - master
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checando que todo ok
      uses: actions/checkout@v2

    - name: Instalando Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Instalando Yarn
      run: npm install -g yarn

    - name: Instalando todo lo necesario del proyecto Angular
      run: yarn install

    - name: Construyendo proyecto Angular
      run: yarn build

    - name: Configurando AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Vaciar el bucket
      run: aws s3 rm s3://skp-socialmedia-chat/ --recursive

    - name: Verificar si el bucket está vacío
      id: check_bucket
      run: |
        IS_BUCKET_EMPTY=$(aws s3 ls s3://skp-socialmedia-chat/ --recursive | wc -l)
        echo "::set-output name=isEmpty::$IS_BUCKET_EMPTY"

    - name: Subiendo contenido de dist/chatvia a Amazon S3
      run: |
        if [ "${{ steps.check_bucket.outputs.isEmpty }}" -eq "0" ]; then
          aws s3 sync dist/chatvia/ s3://skp-socialmedia-chat/ --debug
        else
          echo "El bucket no está vacío. Por favor, comprueba manualmente."
          exit 1
        fi
